version: "3"
services:

  musiccodes:
    image: cgreenhalgh/musiccodes
    networks: 
      - mc-net
    deploy:
      mode: global
    ports:
      - "3000:3000"
    volumes:
      - ./volumes/experiences:/srv/musiccodes/experiences
      - ./volumes/content:/srv/musiccodes/public/content
      - ./logs/musiccodes:/srv/musiccodes/logs
    environment:
      DEFAULT_MPM_SERVER: 'http://mpm:3003'
    depends_on: 
      - mpm
    restart: unless-stopped
    
  
  meld:
    image: cgreenhalgh/meld
    networks: 
      - mc-net
    deploy:
      mode: global
    ports:
      - "5000:5000"
    volumes:
      - ./volumes/score:/root/work/score
    restart: unless-stopped
      
  meld-client:
    image: cgreenhalgh/meld-client
    networks: 
      - mc-net
    deploy:
      mode: global
    ports:
      - "8080:8080"
    restart: unless-stopped
  
  redis:
    image: redis:4.0
    networks:
      - mc-net
    deploy:
      mode: global
    restart: unless-stopped
      
  mpm:
    image: cgreenhalgh/mpm
    networks: 
      - mc-net
    depends_on: 
      - redis
    ports:
      - "3003:3003"
    deploy:
      mode: global
    volumes:
      - ./volumes/templates:/srv/mpm/templates
      - ./logs/mpm:/srv/mpm/logs
    restart: unless-stopped
  
  pedal:
    image: cgreenhalgh/pedal
    networks:
      - mc-net
    depends_on:
      - musiccodes
    deploy:
      mode: global
    command: ["python","pedal.py","http://musiccodes:3000/input"]
    tty: true
    restart: unless-stopped
    
networks:
  mc-net:
