// Generated by CoffeeScript 1.11.1
(function() {
  var Generator;

  Generator = (function() {
    function Generator(title1, config) {
      var layer, ref, ref1, ref10, ref11, ref12, ref13, ref14, ref15, ref2, ref3, ref4, ref5, ref6, ref7, ref8, ref9, video;
      this.title = title1;
      this.preload = [];
      this.config = config;
      this.layers = [
        {
          title: 'background',
          channel: 'v.background',
          defaultUrl: this.content_url(config.forcebackgroundurl, config),
          loop: true,
          fadeIn: (ref = config.backgroundfadein) != null ? ref : 0,
          fadeOut: (ref1 = config.backgroundfadeout) != null ? ref1 : 0,
          crossfade: false
        }, {
          title: 'animation',
          channel: 'v.animate',
          defaultUrl: this.content_url(config.noanimationurl, config),
          loop: false,
          fadeIn: 0,
          fadeOut: 0,
          crossfade: true
        }, {
          title: 'weather',
          channel: 'v.weather',
          loop: true,
          fadeIn: (ref2 = config.weatherfadein) != null ? ref2 : 0,
          fadeOut: (ref3 = config.weatherfadeout) != null ? ref3 : 0,
          crossfade: true
        }, {
          title: 'muzicode',
          channel: 'v.mc',
          loop: false,
          fadeIn: (ref4 = config.muzicodefadein) != null ? ref4 : 0,
          fadeOut: (ref5 = config.muzicodefadeout) != null ? ref5 : 0,
          holdTime: (ref6 = config.muzicodeholdtime) != null ? ref6 : null,
          crossfade: true
        }
      ];
      video = {
        title: 'video',
        channel: 'v.video',
        loop: false,
        fadeIn: 0,
        fadeOut: 0,
        crossfade: false,
        insetTop: (ref7 = config.videoInsetTop) != null ? ref7 : 0,
        insetBottom: (ref8 = config.videoInsetBottom) != null ? ref8 : 0,
        insetLeft: (ref9 = config.videoInsetLeft) != null ? ref9 : 0,
        insetRight: (ref10 = config.videoInsetRight) != null ? ref10 : 0,
        cropTop: (ref11 = config.videoCropTop) != null ? ref11 : 0,
        cropBottom: (ref12 = config.videoCropBottom) != null ? ref12 : 0,
        cropLeft: (ref13 = config.videoCropLeft) != null ? ref13 : 0,
        cropRight: (ref14 = config.videoCropRight) != null ? ref14 : 0
      };
      if (config.videourl != null) {
        video.defaultUrl = config.videourl;
        layer = (ref15 = config.videolayer) != null ? ref15 : 0;
        if (layer > this.layers.length) {
          layer = this.layers.length;
        } else if (layer < 0) {
          layer = 0;
        }
        this.layers.splice(layer, 0, video);
      }
      this.add(config.forcebackgroundurl);
      this.add(config.videourl);
      this.add(config.noanimationurl);
      this.add(config.no_url);
      this.add(config.defaultmuzicodeurl);
      this.add(config.rain_url);
      this.add(config.snow_url);
      this.add(config.sun_url);
      this.add(config.storm_url);
      this.add(config.wind_url);
    }

    Generator.prototype.content_url = function(url, config) {
      if ((url != null) && (config.contenturi != null) && (url.indexOf(':')) < 0 && (url.substring(0, 1)) !== '/') {
        return config.contenturi + url;
      } else {

      }
      return url;
    };

    Generator.prototype.get = function() {
      return {
        title: this.title,
        generated: (new Date()).toISOString(),
        preload: this.preload,
        layers: this.layers
      };
    };

    Generator.prototype.add = function(url) {
      url = this.content_url(url, this.config);
      if ((url != null) && (this.preload.indexOf(url)) < 0) {
        return this.preload.push(url);
      }
    };

    return Generator;

  })();

  module.exports.generator = function(title, config) {
    return new Generator(title, config);
  };

  module.exports.BACKGROUND = 'v.background';

  module.exports.ANIMATION = 'v.animation';

  module.exports.WEATHER = 'v.weather';

  module.exports.MUZICODE = 'v.muzicode';

}).call(this);
