// Generated by CoffeeScript 1.11.1
(function() {
  var event, file, fs, i, j, len, len1, midi, midiFileParser, midifile, output, outputBuffer, ref, track, writeMidi;

  if (process.argv.length !== 3) {
    console.error('Usage: node readmidi.js MIDIFILE');
    process.exit(-1);
  }

  midiFileParser = require('midi-file').parseMidi;

  writeMidi = require('midi-file').writeMidi;

  fs = require('fs');

  midifile = process.argv[2];

  console.log('read ' + midifile);

  file = fs.readFileSync(midifile);

  midi = midiFileParser(file);

  console.log('ok');

  output = writeMidi(midi);

  outputBuffer = new Buffer(output);

  fs.writeFileSync('tmp.mid', outputBuffer);

  console.log('header: ' + (JSON.stringify(midi.header)));

  console.log('' + midi.tracks.length + ' tracks');

  ref = midi.tracks;
  for (i = 0, len = ref.length; i < len; i++) {
    track = ref[i];
    console.log('track:');
    for (j = 0, len1 = track.length; j < len1; j++) {
      event = track[j];
      console.log('  ' + (JSON.stringify(event)));
    }
  }

}).call(this);
