// Generated by CoffeeScript 1.11.1
(function() {
  var event, file, fs, i, j, k, l, len, len1, len2, len3, midi, midiFileParser, midifile, output, outputBuffer, ref, ref1, track, writeMidi;

  if (process.argv.length !== 3) {
    console.error('Usage: node readmidi.js MIDIFILE');
    process.exit(-1);
  }

  midiFileParser = require('midi-file-parser');

  writeMidi = require('midi-file').writeMidi;

  fs = require('fs');

  midifile = process.argv[2];

  console.log('read ' + midifile);

  file = fs.readFileSync(midifile, 'binary');

  midi = midiFileParser(file);

  ref = midi.tracks;
  for (i = 0, len = ref.length; i < len; i++) {
    track = ref[i];
    for (j = 0, len1 = track.length; j < len1; j++) {
      event = track[j];
      event.type = event.subtype;
    }
  }

  console.log('ok');

  output = writeMidi(midi);

  outputBuffer = new Buffer(output);

  fs.writeFileSync('tmp.mid', outputBuffer);

  console.log('header: ' + (JSON.stringify(midi.header)));

  console.log('' + midi.tracks.length + ' tracks');

  ref1 = midi.tracks;
  for (k = 0, len2 = ref1.length; k < len2; k++) {
    track = ref1[k];
    console.log('track:');
    for (l = 0, len3 = track.length; l < len3; l++) {
      event = track[l];
      console.log('  ' + (JSON.stringify(event)));
    }
  }

}).call(this);
